//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string NRC { get; set; }
        public string Email { get; set; }
        public Nullable<int> CityId { get; set; }
        public string TownShip { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> MemberTypeID { get; set; }
        public string VIPMemberId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
