//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRateForTransaction
    {
        public int Id { get; set; }
        public int CurrencyId { get; set; }
        public string TransactionId { get; set; }
        public int ExchangeRate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
