//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftSystem
    {
        public int Id { get; set; }
        public bool IsGWP { get; set; }
        public string Name { get; set; }
        public Nullable<long> MustBuyCostFrom { get; set; }
        public Nullable<long> MustBuyCostTo { get; set; }
        public Nullable<long> MustIncludeProductId { get; set; }
        public Nullable<int> FilterBrandId { get; set; }
        public Nullable<int> FilterCategoryId { get; set; }
        public Nullable<int> FilterSubCategoryId { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<long> GiftProductId { get; set; }
        public long GiftDiscountAmountForGiftProduct { get; set; }
        public long GiftCashAmount { get; set; }
        public long GiftDiscountAmount { get; set; }
        public int GiftDiscountPercent { get; set; }
    }
}
