//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loc_PointRedeemHistory
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int RedeemPoint { get; set; }
        public System.DateTime DateTime { get; set; }
        public int CounterId { get; set; }
        public int CasherId { get; set; }
    }
}
