//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCardRule
    {
        public int Id { get; set; }
        public int MemberTypeId { get; set; }
        public string RangeFrom { get; set; }
        public string RangeTo { get; set; }
        public Nullable<decimal> MCDiscount { get; set; }
        public Nullable<decimal> BDDiscount { get; set; }
    
        public virtual MemberType MemberType { get; set; }
    }
}
