//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string Supplier { get; set; }
        public Nullable<long> ManufacturedCode { get; set; }
        public string LocationInWareHose { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Unit { get; set; }
    }
}
