//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetailInTransaction
    {
        public int Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> TransactionDetailId { get; set; }
        public Nullable<int> PurchaseDetailId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseDetail PurchaseDetail { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
