//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public PurchaseDetail()
        {
            this.PurchaseDeleteLogs = new HashSet<PurchaseDeleteLog>();
            this.PurchaseDetailInTransactions = new HashSet<PurchaseDetailInTransaction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MainPurchaseId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> CurrentQy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> ConvertQty { get; set; }
    
        public virtual MainPurchase MainPurchase { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<PurchaseDeleteLog> PurchaseDeleteLogs { get; set; }
        public virtual ICollection<PurchaseDetailInTransaction> PurchaseDetailInTransactions { get; set; }
    }
}
