//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDeleteLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CounterId { get; set; }
        public Nullable<int> MainPurchaseId { get; set; }
        public Nullable<int> PurchaseDetailId { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string VoucherNo { get; set; }
    
        public virtual Counter Counter { get; set; }
        public virtual MainPurchase MainPurchase { get; set; }
        public virtual PurchaseDetail PurchaseDetail { get; set; }
        public virtual User User { get; set; }
    }
}
