//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPDetail
    {
        public long Id { get; set; }
        public Nullable<long> TransactionDetailID { get; set; }
        public Nullable<long> ParentProductID { get; set; }
        public Nullable<long> ChildProductID { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public string SPDetailID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
