//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConversion
    {
        public int Id { get; set; }
        public int FromProductId { get; set; }
        public decimal FromQty { get; set; }
        public int ToProductId { get; set; }
        public decimal ToQty { get; set; }
        public System.DateTime ConversionDate { get; set; }
        public decimal OnePackQty { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int NormalPurchaseDetailId { get; set; }
        public string MaximumPurchaseDetailId { get; set; }
        public Nullable<int> NormalUnitPurchasePrice { get; set; }
    }
}
