//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsePrePaidDebt
    {
        public int Id { get; set; }
        public string CreditTransactionId { get; set; }
        public string PrePaidDebtTransactionId { get; set; }
        public Nullable<int> UseAmount { get; set; }
        public Nullable<int> CashierId { get; set; }
        public Nullable<int> CounterId { get; set; }
    
        public virtual Counter Counter { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual Transaction Transaction1 { get; set; }
        public virtual User User { get; set; }
    }
}
